package com.nstudiosappdev.games.dashboard.domain.objects

import com.google.gson.annotations.SerializedName

data class GameDetail(
    @SerializedName("id") val id: Int?,
    @SerializedName("slug") val slug: String?,
    @SerializedName("name") val name: String?,
    @SerializedName("description") val description: String?,
    @SerializedName("metacritic") val metacritic: Int?,
    @SerializedName("released") val released: String?,
    @SerializedName("tba") val tba: Boolean?,
    @SerializedName("updated") val updated: String?,
    @SerializedName("background_image") val backgroundImage: String?,
    @SerializedName("background_image_additional") val backgroundImageAdditional: String?,
    @SerializedName("website") val website: String?,
    @SerializedName("rating") val rating: Int?,
    @SerializedName("rating_top") val ratingTop: Int?,
    @SerializedName("ratings") val ratings: List<Rating?>?,
    @SerializedName("reactions") val reactions: Reaction?,
    @SerializedName("added") val added: Int?,
    @SerializedName("added_by_status") val addedByStatus: AddedByStatus?,
    @SerializedName("playTime") val playTime: Int?,
    @SerializedName("screenshots_count") val screenShotsCount: Int?,
    @SerializedName("moviesCount") val moviesCount: Int?,
    @SerializedName("creators_count") val creatorsCount: Int?,
    @SerializedName("achievements_count") val achievementsCount: Int?,
    @SerializedName("parent_achievements_count") val parentAchievementsCount: Int?,
    @SerializedName("reddit_url") val redditUrl: String?,
    @SerializedName("reddit_name") val redditName: String?,
    @SerializedName("reddit_description") val redditDescription: String?,
    @SerializedName("reddit_logo") val redditLogo: String?,
    @SerializedName("reddit_count") val redditCount: Int?,
    @SerializedName("twitch_count") val twitchCount: Int?,
    @SerializedName("youtube_count") val youtubeCount: Int?,
    @SerializedName("reviews_text_count") val reviewsTextCount: Int?,
    @SerializedName("ratings_count") val ratingsCount: Int?,
    @SerializedName("suggestions_count") val suggestionsCount: Int?,
    @SerializedName("alternative_names") val alternativeNames: List<String?>?,
    @SerializedName("metacritic_url") val metacriticUrl: String?,
    @SerializedName("parents_count") val parentsCount: Int?,
    @SerializedName("additions_count") val additionsCount: Int?,
    @SerializedName("game_series_count") val gameSeriesCount: Int?,
    @SerializedName("user_game") val userGame: String?,
    @SerializedName("reviews_count") val reviewsCount: Int?,
    @SerializedName("saturatedColor") val saturedColor: String?,
    @SerializedName("dominantColor") val dominantColor: String?,
    @SerializedName("parent_platforms") val parentPlatforms: List<PlatformDetail?>?,
    @SerializedName("platforms") val platforms: List<Platform?>?,
    @SerializedName("stores") val stores: List<Store?>?,
    @SerializedName("developers") val developers: List<Developer?>?,
    @SerializedName("genres") val genres: List<Genre?>?,
    @SerializedName("tags") val tags: List<Tag?>?,
    @SerializedName("publishers") val publishers: List<Publisher?>?,
    @SerializedName("esrb_rating") val esrbRating: EsrbRating?,
    @SerializedName("clip") val clip: Clip?,
    @SerializedName("description_raw") val descriptionRaw: String?

)

data class Reaction(
    @SerializedName("1") val reaction1: Int?,
    @SerializedName("2") val reaction2: Int?,
    @SerializedName("3") val reaction3: Int?,
    @SerializedName("4") val reaction4: Int?,
    @SerializedName("5") val reaction5: Int?,
    @SerializedName("6") val reaction6: Int?,
    @SerializedName("7") val reaction7: Int?,
    @SerializedName("8") val reaction8: Int?,
    @SerializedName("9") val reaction9: Int?,
    @SerializedName("10") val reaction10: Int?,
    @SerializedName("11") val reaction11: Int?,
    @SerializedName("12") val reaction12: Int?,
    @SerializedName("13") val reaction13: Int?,
    @SerializedName("14") val reaction14: Int?,
    @SerializedName("15") val reaction15: Int?,
    @SerializedName("16") val reaction16: Int?,
    @SerializedName("17") val reaction17: Int?,
    @SerializedName("18") val reaction18: Int?,
    @SerializedName("19") val reaction19: Int?,
    @SerializedName("20") val reaction20: Int?,
    @SerializedName("21") val reaction21: Int?
)

data class EsrbRating(
    @SerializedName("id") val id: Int?,
    @SerializedName("name") val name: String?,
    @SerializedName("slug") val slug :String?
)
